[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_movie_review_program = "BaDUDhQ922Tc6fhVEnyk5Lcus3yimoviUqxwLsi1Jc1R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ibrahimarshad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
